/// scrNetworkingGameSpecificConstants()

// object types
globalvar PLAYER1, PLAYER2, BIG_LAKE_2_LEFT, BIG_LAKE_2_RIGHT, BIG_LAKE_3, BUILDING_1, BUILDING_2;
globalvar BUILDING_3, BUILDING_4, MINE, BULLET, PLAYER, HEALTH, AMMO, TRACKS, SAND_BIG_LAKE_2_LEFT;
globalvar SAND_BIG_LAKE_2_RIGHT, SAND_BIG_LAKE_3, FLAG_RED, FLAG_BLUE, HOME_BASE_RED, HOME_BASE_BLUE;
PLAYER1 = 0;
PLAYER2 = 1;
BUILDING_1 = 3;
BUILDING_2 = 4;
BUILDING_3 = 5;
BUILDING_4 = 6;
MINE = 7;
BULLET = 8;
HEALTH = 9;
AMMO = 10;
TRACKS = 11;
SAND_BIG_LAKE_2_LEFT = 12;
SAND_BIG_LAKE_2_RIGHT = 13;
SAND_BIG_LAKE_3 = 14;
FLAG_RED = 15;
FLAG_BLUE = 16;
HOME_BASE_RED = 17;
HOME_BASE_BLUE = 18;
BIG_LAKE_2_LEFT = 19;
BIG_LAKE_2_RIGHT = 20;
BIG_LAKE_3 = 21;

// sound types
globalvar SOUND_MAIN_GUN, SOUND_ITEM, SOUND_FLAG, SOUND_FANFARE, SOUND_EXPLOSION;
SOUND_MAIN_GUN = 0
SOUND_ITEM = 1
SOUND_FLAG = 2
SOUND_FANFARE = 3
SOUND_EXPLOSION = 4
